---
title: "all_measures"
author: Jeffrey Choi
output: html_document
---

Plots the average cortical brain thickness by region
```{r}
#| warning: false

# lets work with cortical thickness first
data_dir <- '/Users/jeffee/Library/CloudStorage/Box-Box/ABCD Tabulated Data/5.1/core/'

setwd(data_dir)

# LOAD DATA
# Demographic variables and propensity weights
demog <- read.csv("abcd-general/abcd_p_demo.csv", na.strings = c(999, 777))
# Age in months, Site ID (ABCD Study Design Variables), Family ID
study_covars <- read.csv("abcd-general/abcd_y_lt.csv")
# desikan atlas, cortical thickness
dat.mri.ct = read.csv('imaging/mri_y_smr_thk_dsk.csv')

# basic cleaning for demographic variables
demog_clean <- demog |>
  # select broad demographics
  select(src_subject_id, eventname, starts_with("demo_brthdat_v2"), demo_sex_v2, race_ethnicity) |>
  # fill in race and sex first (avoid losing demog info due to filtering eventname)
  group_by(src_subject_id) %>%
  mutate(
    race_ethnicity = first(na.omit(race_ethnicity)),
    demo_sex_v2 = first(na.omit(demo_sex_v2))
  ) %>%
  ungroup() %>%
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1")) |>
  mutate(
    # clean age variable
    age = case_when(
      eventname == "baseline_year_1_arm_1" ~ trunc(demo_brthdat_v2), # remove decimals 
      eventname %in% c("2_year_follow_up_y_arm_1", "4_year_follow_up_y_arm_1") ~
        trunc(demo_brthdat_v2_l)),
    # broad race/ethnicity categories
    race_ethnicity = case_match(
      race_ethnicity,
      1 ~ "White",
      2 ~ "Black",
      3 ~ "Hispanic",
      4 ~ "Asian",
      5 ~ "Other"
    ),
    # recode sex variable
    sex = factor(demo_sex_v2),
    sex = fct_recode(
      sex,
      "Male" = "1",
      "Female" = "2",
      "Intersex-Male" = "3"
    )) %>%
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1"))


thickness <- dat.mri.ct |>
  # join mri data to demographics
  left_join(demog_clean, by = join_by("eventname", "src_subject_id")) |>
  # join to study covariates
  left_join(study_covars, by = join_by("eventname", "src_subject_id")) |>
  select(src_subject_id, eventname, starts_with("smri"), age, sex, race_ethnicity 
         , site_id_l, interview_age) |>
  # remove ages less than 8 and more than 16
  filter(age < 16 & age > 8) |>
  mutate(interview_age = as.numeric(interview_age))

# removed single NA race and intersex individuals (3)
thickness <- thickness %>%
  filter(sex != "Intersex-Male") %>%
  filter(!is.na(race_ethnicity))
```

```{r}
# This returns the real brain region name from abcd abbreviation

dk_abv_to_names = read.csv("~/Documents/GitHub/Normative_brain_development_and_deviations_for_adolescents/exploration/additional_files/dk_abv_to_names.csv")
# returns region name from abcd abv
get_name <- function(dk_abv_to_names, abv){
  (dk_abv_to_names %>% filter(var_name == abv))$region
}

# example
get_name(dk_abv_to_names, abv = "cdacatelh")
```

```{r}
# compute overall average for each brain region measurement
avg_thickness <- thickness %>%
  group_by(sex, eventname) %>%
  summarise(across(
    .cols = starts_with("smri_"),  # assumes brain region columns start with "smri_"
    .fns = mean,
    .names = "avg_{.col}"
  ), .groups = "drop") %>%
  # rename mri columns (removes smri_thick_cdk)
  rename_with(
    .fn = ~ sub("^avg_smri_thick_cdk_", "avg_", .x),
    .cols = starts_with("avg_smri_thick_cdk_")
  )


avg_thickness<- avg_thickness[1:(length(avg_thickness)-3)] # removes mean lh, rh, and whole
```

```{r}
# renames abcd abbreviation to real name (preserving hemi with '_lr' or _rh')
new_names <- names(avg_thickness) %>%
  setNames(., .) %>%
  map_chr(function(col_name) {
    if (str_starts(col_name, "avg_")) {
      abv <- str_remove(col_name, "^avg_")
      # extract hemisphere
      hemi <- case_when(
        str_ends(abv, "lh") ~ "_lh",
        str_ends(abv, "rh") ~ "_rh"
      )
      real_name <- get_name(dk_abv_to_names, str_remove(abv, "_lh$|_rh$"))
      return(paste0(real_name, hemi))
    } else {
      return(col_name)
    }
  })

# Rename the dataframe with new names
avg_thickness <- avg_thickness %>% rename_with(~ new_names)
```

```{r}
# pivot wide to get regions as values not as feature names
avg_thickness_wide <- avg_thickness %>%
  pivot_longer(cols = 3:70, names_to = "region", values_to = "thickness") %>%
  mutate(hemi = case_when(
    str_ends(region, "_lh") ~ "left",
    str_ends(region, "_rh") ~ "right")) %>%
  mutate(region = sub("_lh", "", region)) %>%
  mutate(region = sub("_rh", "", region))
```

Manually changes a single region to check if the model works
```{r}
avg_thickness_wide <- avg_thickness_wide %>%
  mutate(
    thickness = case_when(
      sex == "Male" &
      eventname == "baseline_year_1_arm_1" &
      hemi == "left" &
      region == "bankssts" ~ 5, #value
      TRUE ~ thickness
    )
  )

```

Baseline average corical thickness by region
```{r}
# brain plots with ggseg
avg_thickness_wide %>%
  filter(eventname == "baseline_year_1_arm_1") %>%
  group_by(sex) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = thickness)) +
  facet_wrap(~sex) +
  scale_fill_gradientn(
    name = "Cortical Thickness (mm)", 
    colors = hcl.colors(10, "purple-yellow"), # use this to change color
  ) +
  theme_void()

```

Year 2 average corical thickness by region
```{r}
# brain plots with ggseg
avg_thickness_wide %>%
  filter(eventname == "2_year_follow_up_y_arm_1") %>%
  group_by(sex) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = thickness)) +
  facet_wrap(~sex) +
  scale_fill_gradientn(
    name = "Cortical Thickness (mm)", 
    colors = hcl.colors(10, "purple-yellow"), # use this to change color
  ) +
  theme_void()

```
Year 2 average corical thickness by region
```{r}
# brain plots with ggseg
avg_thickness_wide %>%
  filter(eventname == "4_year_follow_up_y_arm_1") %>%
  group_by(sex) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = thickness)) +
  facet_wrap(~sex) +
  scale_fill_gradientn(
    name = "Cortical Thickness (mm)", 
    colors = hcl.colors(10, "purple-yellow"), # use this to change color
  ) +
  theme_void()

```


