---
title: "area_centiles_all_measures"
author: Jeffrey Choi
output: html_document
---

```{r}
library(tidyverse)
library(forcats)
library(gamlss)
library(gamlss.data)
library(gamlss.dist)
library(gamlss.foreach)
library(gamlss.ggplots)
library(readr)
library(dplyr)
```

## Model 20 - family: Box-Cox power exp
```{r}
#input: raw data files for male and female
#output: list of length 2 for models. Order is list(male, female)
model_20 <- function(data_male, data_female){
# initial model for average thickness using gamlss
# P-spline smoothing functions
area_model20_male <- gamlss(
  outcome ~ pb(interview_age) + gamlss::random(src_subject_id), # random subject effect
  sigma.formula =~ cs(interview_age),
  
  family = BCT(mu.link = "log", # to stay positive
               sigma.link = "log", # to stay positive
               nu.link = "identity", 
               tau.link = "identity"), 
  data = data_male)

# initial model for average thickness using gamlss
# P-spline smoothing functions
area_model20_male <- gamlss(
  outcome ~ pb(interview_age) + gamlss::random(src_subject_id), # random subject effect
  # mu, sigma, nu, tau with cubic splines with previously collected degrees of freedom
  sigma.formula =~ cs(interview_age),
  
  family = BCT(mu.link = "log", # to stay positive
               sigma.link = "log", # to stay positive
               nu.link = "identity", 
               tau.link = "identity"), 
  data = data_female)
  output <- list(area_model20_male,area_model20_female)
  return (output)
}

```

```{r}
# Collecting centile scores for overall mean male
#input: data frame and model for the inputed data frame
#output: data frame with model parameters saved in new columns
add_parameters <- function(df, model){

df$mu <- predict(model,
                                        what = "mu",
                                        #newdata = df,
                                        type = "response")
df$sigma <- predict(model,
                                           what = "sigma",
                                           #newdata = df,
                                           type = "response")

df$nu <- predict(model,
                                        what = "nu",
                                        #newdata = df,
                                        type = "response")

df$tau <- predict(model,
                                        what = "tau",
                                        #newdata = df,
                                        type = "response")

df$centile <- with(model,pBCPE(df$outcome,
    mu = df$mu,
    sigma = df$sigma,
    nu = df$nu,
    tau = df$tau))

return(df)
}

```


Data preproccessing
```{r}
#| warning: false

# lets work with cortical thickness first
data_dir <- '~/Library/CloudStorage/Box-Box/ABCD Tabulated Data/5.1/core'

setwd(data_dir)

# LOAD DATA
# Demographic variables and propensity weights
demog <- read.csv("abcd-general/abcd_p_demo.csv", na.strings = c(999, 777))
# Age in months, Site ID (ABCD Study Design Variables), Family ID
study_covars <- read.csv("abcd-general/abcd_y_lt.csv")
# desikan atlas, cortical thickness
dat.mri.sa <- read.csv('imaging/mri_y_smr_area_dsk.csv')

list_of_sa_regions <- colnames(dat.mri.sa)[3:ncol(dat.mri.sa)] # this is important

# basic cleaning for demographic variables
demog_clean <- demog |>
  # select broad demographics
  select(src_subject_id, eventname, starts_with("demo_brthdat_v2"), demo_sex_v2, race_ethnicity) |>
  # fill in race and sex first (avoid losing demog info due to filtering eventname)
  group_by(src_subject_id) %>%
  mutate(
    race_ethnicity = first(na.omit(race_ethnicity)),
    demo_sex_v2 = first(na.omit(demo_sex_v2)),
    src_subject_id = factor(src_subject_id)
  ) %>%
  ungroup() %>%
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1")) |>
  mutate(
    # clean age variable
    age = case_when(
      eventname == "baseline_year_1_arm_1" ~ trunc(demo_brthdat_v2), # remove decimals 
      eventname %in% c("2_year_follow_up_y_arm_1", "4_year_follow_up_y_arm_1") ~
        trunc(demo_brthdat_v2_l)),
    # broad race/ethnicity categories
    race_ethnicity = case_match(
      race_ethnicity,
      1 ~ "White",
      2 ~ "Black",
      3 ~ "Hispanic",
      4 ~ "Asian",
      5 ~ "Other"
    ),
    # recode sex variable
    sex = factor(demo_sex_v2),
    sex = fct_recode(
      sex,
      "Intersex-Male" = "3"
    )) %>%
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1"))


area <- dat.mri.sa |>
  # join mri data to demographics
  left_join(demog_clean, by = join_by("eventname", "src_subject_id")) |>
  # join to study covariates
  left_join(study_covars, by = join_by("eventname", "src_subject_id")) |>
  select(src_subject_id, eventname, starts_with("smri"), age, sex, race_ethnicity 
         , site_id_l, interview_age) |>
  # remove ages less than 8 and more than 16
  filter(age < 16 & age > 8) |>
  mutate(interview_age = as.numeric(interview_age))

# create baseline age column for longComBat
baseline_ages <- area %>%
  mutate(baseline_age = interview_age / 12) %>%
  group_by(src_subject_id) %>%
  mutate(baseline_age = first(baseline_age)) %>%
  pull(baseline_age)

# removed single NA race and intersex individuals (3)
area <- area %>%
  mutate(baseline_age = baseline_ages) %>%
  filter(sex != "Intersex-Male") %>%
  filter(!is.na(race_ethnicity))
```

```{r}
if("package:tidyverse" %in% search()){
  detach("package:tidyverse", unload = TRUE)
}

library(longCombat)

simdata_combat <- longCombat(idvar='src_subject_id', 
                             timevar='interview_age',
                             batchvar='site_id_l', 
                             features=list_of_sa_regions, 
                             formula='sex + baseline_age',
                             ranef='(1|src_subject_id)', # random individual effect intercept
                             data=area)
```

```{r}
library(tidyverse)

area_harmonized <- simdata_combat$data_combat

area_plus_harmonized <- merge(area, area_harmonized, by=c('src_subject_id', "interview_age", "site_id_l"))
area_plus_harmonized <- area_plus_harmonized %>% mutate(src_subject_id = factor(src_subject_id))

# adds sex and other cols
area_harmonized <- area_plus_harmonized %>%
  select(-matches("^smri(?!.*\\.combat$)", perl = TRUE)) %>% 
  mutate(src_subject_id = factor(src_subject_id))

```

```{r}
result <- NULL
brain_regions_model <- list() # idk if i need this anymore
final_file_male  <- data.frame(src_subject_id = factor(),	race_ethnicity = character()	,interview_age_baseline_year_1_arm_1= double(),	interview_age_2_year_follow_up_y_arm_1= double(),	interview_age_4_year_follow_up_y_arm_1= double(),	outcome_baseline_year_1_arm_1= double(),	outcome_2_year_follow_up_y_arm_1= double(),	outcome_4_year_follow_up_y_arm_1= double(),	centile_baseline_year_1_arm_1= double(),	centile_2_year_follow_up_y_arm_1= double(),	centile_4_year_follow_up_y_arm_1= double(),	residual_baseline_year_1_arm_1= double(),	residual_2_year_follow_up_y_arm_1= double(),	residual_4_year_follow_up_y_arm_1= double(), current_col_name= character())

final_file_female  <- data.frame(src_subject_id = factor(),	race_ethnicity = character()	,interview_age_baseline_year_1_arm_1= double(),	interview_age_2_year_follow_up_y_arm_1= double(),	interview_age_4_year_follow_up_y_arm_1= double(),	outcome_baseline_year_1_arm_1= double(),	outcome_2_year_follow_up_y_arm_1= double(),	outcome_4_year_follow_up_y_arm_1= double(),	centile_baseline_year_1_arm_1= double(),	centile_2_year_follow_up_y_arm_1= double(),	centile_4_year_follow_up_y_arm_1= double(),	residual_baseline_year_1_arm_1= double(),	residual_2_year_follow_up_y_arm_1= double(),	residual_4_year_follow_up_y_arm_1= double(), current_col_name= character())
#View(final_file_male)

for(i in 9:ncol(area_harmonized)){ #ncol(thickness_harmonized) goes over the entire data set
  
  len <- length(brain_regions_model)  # idk if i need this anymore
  current_col_name <- colnames(area_harmonized)[i]
  print(current_col_name)
  # groups by sex
  area_harmonized_male <- area_harmonized %>% 
    filter(sex == 2) %>%
    select(src_subject_id, interview_age, race_ethnicity, all_of(current_col_name)) %>% ## changed smri_thick_cdk_mean.comabat to current_col
    rename(outcome = current_col_name)
  
  area_harmonized_female <- area_harmonized %>%
    filter(sex == 1) %>%
    select(src_subject_id, interview_age, race_ethnicity, all_of(current_col_name)) %>% ## changed smri_thick_cdk_mean.comabat to current_col 
    rename(outcome = current_col_name)
      
  lms_model_m <- lms(outcome, # current brain region for female data
                  interview_age, 
                  data = area_harmonized_male, 
                  trans.x = TRUE, 
                  k = 2)

  lms_model_f <- lms(outcome,# current brain region for female data
                  interview_age, 
                  data = area_harmonized_female, 
                  trans.x = TRUE, 
                  k = 2)
  
  area_model21 <- model_21(area_harmonized_male, area_harmonized_female ) # thickness model for male and female

  # Collecting centile scores for overall mean male

  area_harmonized_male <- add_parameters(area_harmonized_male, area_model20[[1]]) ## male 
  
  area_harmonized_male$fitted <- fitted(area_model20[[1]], what = "mu",type = "response")
  area_harmonized_male$residual <-
    area_harmonized_male$outcome - area_harmonized_male$fitted

  area_harmonized_female <- add_parameters(area_harmonized_female, area_model20[[2]]) ## female
  
  area_harmonized_female$fitted <- fitted(area_model20[[2]], what = "mu",type = "response")
  area_harmonized_female$residual <-
    area_harmonized_female$outcome - area_harmonized_female$fitted
  
  # adds eventname into df for pivot widering
  area_centile_male <- area_harmonized_male %>%
  left_join(area_harmonized %>%
              filter(sex == 2) %>%
              select(src_subject_id, interview_age, eventname ),
            by = c("src_subject_id", "interview_age"))
# creates centiles df for gender 
area_centile_female <- area_harmonized_female%>%
  left_join(area_harmonized %>%
              filter(sex == 1) %>%
              select(src_subject_id, interview_age, eventname),
            by = c("src_subject_id", "interview_age"))

rm(area_centile_male_wider)

  area_centile_male_wider <- area_centile_male %>%
  select(
    src_subject_id, eventname, interview_age,
    outcome, centile, race_ethnicity, residual
  ) %>%
  pivot_wider(
    names_from = eventname,
    values_from = c(interview_age, outcome, centile, residual)
  )%>%
    mutate(current_col_name)

area_centile_female_wider <- area_centile_female %>%
  select(src_subject_id, eventname, interview_age,
         outcome, centile, race_ethnicity, residual) %>%
  pivot_wider(
    names_from = eventname,
    values_from = c(interview_age, outcome, centile, residual)
    ) %>%
    mutate(current_col_name)

  final_file_male <- final_file_male%>%
    union(area_centile_male_wider)
  
  final_file_female <- final_file_female%>%
    union(area_centile_female_wider)
  print("###########################################################################################")
  print(current_col_name)
  print("###########################################################################################")

}
print(final_file_male)
```

```{r}
write.csv(final_file_male, file = file.path("~/Library/CloudStorage/Box-Box/area", "final_data_male.csv"), row.names = FALSE)

write.csv(final_file_female, file = file.path("~/Library/CloudStorage/Box-Box/area", "final_data_female.csv"), row.names = FALSE)
```