---
title: "centiles"
author: Jeffrey Choi
output: html_document
---


```{r}
library(dplyr)
library(longCombat)
library(forcats)
library(gamlss)
library(gamlss.data)
library(gamlss.dist)
library(gamlss.foreach)
library(gamlss.ggplots)
```

Data preproccessing
```{r}
#| warning: false

# lets work with cortical thickness first
data_dir <- '/Users/jeffee/Library/CloudStorage/Box-Box/ABCD Tabulated Data/5.1/core/'

setwd(data_dir)

# LOAD DATA
# Demographic variables and propensity weights
demog <- read.csv("abcd-general/abcd_p_demo.csv", na.strings = c(999, 777))
# Age in months, Site ID (ABCD Study Design Variables), Family ID
study_covars <- read.csv("abcd-general/abcd_y_lt.csv")
# desikan atlas, cortical thickness
dat.mri.ct = read.csv('imaging/mri_y_smr_thk_dsk.csv')

list_of_ct_regions <- colnames(dat.mri.ct)[3:ncol(dat.mri.ct)] # this is important


# basic cleaning for demographic variables
demog_clean <- demog |>
  # select broad demographics
  select(src_subject_id, eventname, starts_with("demo_brthdat_v2"), demo_sex_v2, race_ethnicity) |>
  # fill in race and sex first (avoid losing demog info due to filtering eventname)
  group_by(src_subject_id) %>%
  mutate(
    race_ethnicity = first(na.omit(race_ethnicity)),
    demo_sex_v2 = first(na.omit(demo_sex_v2)),
    src_subject_id = factor(src_subject_id)
  ) %>%
  ungroup() %>%
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1")) |>
  mutate(
    # clean age variable
    age = case_when(
      eventname == "baseline_year_1_arm_1" ~ trunc(demo_brthdat_v2), # remove decimals 
      eventname %in% c("2_year_follow_up_y_arm_1", "4_year_follow_up_y_arm_1") ~
        trunc(demo_brthdat_v2_l)),
    # broad race/ethnicity categories
    race_ethnicity = case_match(
      race_ethnicity,
      1 ~ "White",
      2 ~ "Black",
      3 ~ "Hispanic",
      4 ~ "Asian",
      5 ~ "Other"
    ),
    # recode sex variable
    sex = factor(demo_sex_v2),
    sex = fct_recode(
      sex,
      "Intersex-Male" = "3"
    )) %>%
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1"))


thickness <- dat.mri.ct |>
  # join mri data to demographics
  left_join(demog_clean, by = join_by("eventname", "src_subject_id")) |>
  # join to study covariates
  left_join(study_covars, by = join_by("eventname", "src_subject_id")) |>
  select(src_subject_id, eventname, starts_with("smri"), age, sex, race_ethnicity 
         , site_id_l, interview_age) |>
  # remove ages less than 8 and more than 16
  filter(age < 16 & age > 8) |>
  mutate(interview_age = as.numeric(interview_age))

# create baseline age column for longComBat
baseline_ages <- thickness %>%
  mutate(baseline_age = interview_age / 12) %>%
  group_by(src_subject_id) %>%
  mutate(baseline_age = first(baseline_age)) %>%
  pull(baseline_age)

# removed single NA race and intersex individuals (3)
thickness <- thickness %>%
  mutate(baseline_age = baseline_ages) %>%
  filter(sex != "Intersex-Male") %>%
  filter(!is.na(race_ethnicity))
```

```{r}
if("package:tidyverse" %in% search()){
  detach("package:tidyverse", unload = TRUE)
}

library(longCombat)

simdata_combat <- longCombat(idvar='src_subject_id', 
                             timevar='interview_age',
                             batchvar='site_id_l', 
                             features=list_of_ct_regions, 
                             formula='sex + baseline_age',
                             ranef='(1|src_subject_id)', # random individual effect intercept
                             data=thickness)
```
```{r}
library(tidyverse)
```

```{r}
thickness_harmonized <- simdata_combat$data_combat

thickness_plus_harmonized <- merge(thickness, thickness_harmonized, by=c('src_subject_id', "interview_age", "site_id_l"))
thickness_plus_harmonized <- thickness_plus_harmonized %>% mutate(src_subject_id = factor(src_subject_id))

# adds sex and other cols
thickness_harmonized <- thickness_plus_harmonized %>%
  select(-matches("^smri(?!.*\\.combat$)", perl = TRUE)) %>% 
  mutate(src_subject_id = factor(src_subject_id))

# groups by sex
# ONLY USE MEAN COL
thickness_harmonized_male <- thickness_harmonized %>% 
  filter(sex == 2) %>%
  select(src_subject_id, interview_age, race_ethnicity, smri_thick_cdk_mean.combat)

thickness_harmonized_female <- thickness_harmonized %>%
  filter(sex == 1) %>%
  select(src_subject_id, interview_age, race_ethnicity, smri_thick_cdk_mean.combat)

# used to get power for x transformation
lms_model_m <- lms(smri_thick_cdk_mean.combat, 
                 interview_age, 
                 data = thickness_harmonized_male, 
                 trans.x = TRUE, 
                 k = 2)

lms_model_f <- lms(smri_thick_cdk_mean.combat, 
                 interview_age, 
                 data = thickness_harmonized_female, 
                 trans.x = TRUE, 
                 k = 2)
```

## Model 21 - family: Box-Cox t (power transformation on predictor)
```{r}
# initial model for average thickness using gamlss
# P-spline smoothing functions
thickness_model21_male <- gamlss(
  smri_thick_cdk_mean.combat ~ pb(interview_age^lms_model_m$power) + gamlss::random(src_subject_id), # random subject effect
  # mu, sigma, nu, tau with cubic splines with previously collected degrees of freedom
  sigma.formula =~ cs(interview_age),
  
  family = BCT(mu.link = "log", # to stay positive
               sigma.link = "log", # to stay positive
               nu.link = "identity", 
               tau.link = "identity"), 
  data = thickness_harmonized_male)

# initial model for average thickness using gamlss
# P-spline smoothing functions
thickness_model21_female <- gamlss(
  smri_thick_cdk_mean.combat ~ pb(interview_age^lms_model_f$power) + gamlss::random(src_subject_id), # random subject effect
  # mu, sigma, nu, tau with cubic splines with previously collected degrees of freedom
  sigma.formula =~ cs(interview_age),
  
  family = BCT(mu.link = "log", # to stay positive
               sigma.link = "log", # to stay positive
               nu.link = "identity", 
               tau.link = "identity"), 
  data = thickness_harmonized_female)
```

## Model 21 Male Statistics - family: Box-Cox t (power transformation on predictor)
```{r}
#| warning: false

summary(thickness_model21_male)

fitted_centiles_legend(
  thickness_model21_male,
  cent = c(2.5, 50, 97.5),
  xvar = thickness_harmonized_male %>% dplyr::select(interview_age) %>% pull) +
  labs(x = "Interview Age (Months)",
       y = "Cortical Thickness (mm)") +
  theme_minimal()

round(Q.stats(
  thickness_model21_male,
  xvar = thickness_harmonized_male$interview_age,
  zvals = TRUE), 3)

wp(thickness_model21_male, xvar = thickness_harmonized_male$interview_age)
```

## Model 21 Female Statistics - family: Box-Cox t (power transformation on predictor)
```{r}
#| warning: false

summary(thickness_model21_female)

fitted_centiles_legend(
  thickness_model21_female,
  cent = c(2.5, 50, 97.5),
  xvar = thickness_harmonized_female %>% dplyr::select(interview_age) %>% pull) +
  labs(x = "Interview Age (Months)",
       y = "Cortical Thickness (mm)") +
  theme_minimal()

round(Q.stats(
  thickness_model21_female,
  xvar = thickness_harmonized_female$interview_age,
  zvals = TRUE), 3)
```

```{r}
# Collecting centile scores for overall mean male
thickness_harmonized_male_newdata <- thickness_harmonized_male

# having newdata gives an assumption warning? idk just commented it out
thickness_harmonized_male$mu <- predict(thickness_model21_male,
                                        what = "mu",
                                        #newdata = thickness_harmonized_male,
                                        type = "response")

thickness_harmonized_male$sigma <- predict(thickness_model21_male,
                                           what = "sigma",
                                           #newdata = thickness_harmonized_male,
                                           type = "response")

thickness_harmonized_male$nu <- predict(thickness_model21_male,
                                        what = "nu",
                                        #newdata = thickness_harmonized_male,
                                        type = "response")

thickness_harmonized_male$tau <- predict(thickness_model21_male,
                                        what = "tau",
                                        #newdata = thickness_harmonized_male,
                                        type = "response")

thickness_harmonized_male$centile <- with(thickness_model21_male,
                                                  pBCT(thickness_harmonized_male$smri_thick_cdk_mean.combat,
    mu = thickness_harmonized_male$mu,
    sigma = thickness_harmonized_male$sigma,
    nu = thickness_harmonized_male$nu,
    tau = thickness_harmonized_male$tau))
```


```{r}
# Collecting centile scores for overall mean female
thickness_harmonized_female$mu <- predict(thickness_model21_female,
                                        what = "mu",
                                        #newdata = thickness_harmonized_female,
                                        type = "response")

thickness_harmonized_female$sigma <- predict(thickness_model21_female,
                                           what = "sigma",
                                           #newdata = thickness_harmonized_female,
                                           type = "response")

thickness_harmonized_female$nu <- predict(thickness_model21_female,
                                        what = "nu",
                                        #newdata = thickness_harmonized_female,
                                        type = "response")

thickness_harmonized_female$tau <- predict(thickness_model21_female,
                                        what = "tau",
                                        #newdata = thickness_harmonized_female,
                                        type = "response")

thickness_harmonized_female$centile <- with(thickness_model21_female,
                                                    pBCT(thickness_harmonized_female$smri_thick_cdk_mean.combat,
    mu = thickness_harmonized_female$mu,
    sigma = thickness_harmonized_female$sigma,
    nu = thickness_harmonized_female$nu,
    tau = thickness_harmonized_female$tau))
```

```{r}
# adds eventname into df for pivot widering
thickness_centile_male <- thickness_harmonized_male %>%
  left_join(thickness_harmonized %>%
              filter(sex == 2) %>%
              select(src_subject_id, interview_age, eventname, ),
            by = c("src_subject_id", "interview_age"))

thickness_centile_female <- thickness_harmonized_female%>%
  left_join(thickness_harmonized %>%
              filter(sex == 1) %>%
              select(src_subject_id, interview_age, eventname),
            by = c("src_subject_id", "interview_age"))
```

```{r}
thickness_centile_male_wider <- thickness_centile_male %>%
  select(
    src_subject_id, eventname, interview_age,
    smri_thick_cdk_mean.combat, centile, race_ethnicity
  ) %>%
  pivot_wider(
    names_from = eventname,
    values_from = c(interview_age, smri_thick_cdk_mean.combat, centile)
  ) %>%
  rename(
    interview_age_baseline = interview_age_baseline_year_1_arm_1,
    interview_age_year_2 = interview_age_2_year_follow_up_y_arm_1,
    interview_age_year_4 = interview_age_4_year_follow_up_y_arm_1,
    smri_thick_cdk_mean.combat_baseline = smri_thick_cdk_mean.combat_baseline_year_1_arm_1,
    smri_thick_cdk_mean.combat_year_2 = smri_thick_cdk_mean.combat_2_year_follow_up_y_arm_1,
    smri_thick_cdk_mean.combat_year_4 = smri_thick_cdk_mean.combat_4_year_follow_up_y_arm_1,
    centile_baseline = centile_baseline_year_1_arm_1,
    centile_year_2 = centile_2_year_follow_up_y_arm_1,
    centile_year_4 = centile_4_year_follow_up_y_arm_1,
    )

thickness_centile_female_wider <- thickness_centile_female %>%
  select(
    src_subject_id, eventname, interview_age,
         smri_thick_cdk_mean.combat, centile, race_ethnicity
    ) %>%
  pivot_wider(
    names_from = eventname,
    values_from = c(interview_age, smri_thick_cdk_mean.combat, centile)
    ) %>%
  rename(
    interview_age_baseline = interview_age_baseline_year_1_arm_1,
    interview_age_year_2 = interview_age_2_year_follow_up_y_arm_1,
    interview_age_year_4 = interview_age_4_year_follow_up_y_arm_1,
    smri_thick_cdk_mean.combat_baseline = smri_thick_cdk_mean.combat_baseline_year_1_arm_1,
    smri_thick_cdk_mean.combat_year_2 = smri_thick_cdk_mean.combat_2_year_follow_up_y_arm_1,
    smri_thick_cdk_mean.combat_year_4 = smri_thick_cdk_mean.combat_4_year_follow_up_y_arm_1,
    centile_baseline = centile_baseline_year_1_arm_1,
    centile_year_2 = centile_2_year_follow_up_y_arm_1,
    centile_year_4 = centile_4_year_follow_up_y_arm_1,
    )
```

Lets look into some individual level attributes

```{r}
glmm_male <- lmer(data = thickness_centile_male,
                centile ~ interview_age + race_ethnicity + (1|src_subject_id))

summary(glmm_male)
```
```{r}
glmm_female <- lmer(data = thickness_centile_female,
                centile ~ interview_age + race_ethnicity + (1|src_subject_id))

summary(glmm_female)
```

```{r}
lm_male_changes <- lm(
  data = thickness_centile_male_wider %>%
    mutate(
      delta_centile_2 =
        (centile_year_2 - centile_baseline) / (interview_age_year_2 - interview_age_baseline)
    ) %>%
    mutate(
      delta_centile_4 =
        (centile_year_4 - centile_year_2) / (interview_age_year_4 - interview_age_year_2)
    ) %>%
    mutate(
      delta_centile_all =
        (centile_year_4 - centile_baseline) / (interview_age_year_4 - interview_age_baseline)
    ),
  delta_centile_2 ~ interview_age_year_2 + race_ethnicity
)

summary(lm_male_changes)
```

```{r}
baseline <- thickness_centile_male_wider %>%
  drop_na() %>% 
  mutate(centile_bin = cut(centile_baseline, breaks = seq(0, 1, by = 0.25), include.lowest = TRUE), timepoint = "baseline"
         )

year_two <- thickness_centile_male_wider %>%
  drop_na() %>% 
  mutate(centile_bin = cut(centile_year_2, breaks = seq(0, 1, by = 0.25), include.lowest = TRUE), timepoint = "Year 2")

year_four <- thickness_centile_male_wider %>%
  drop_na() %>% 
  mutate(centile_bin = cut(centile_year_4, breaks = seq(0, 1, by = 0.25), include.lowest = TRUE),timepoint = "Year 4")

  combined_df <- bind_rows(baseline, year_two, year_four)

ggplot(combined_df, aes(x= centile_bin, fill= race_ethnicity))+ 
  geom_bar(position = "stack") + 
  facet_wrap(~ timepoint) +
  labs(
    title = "Centile Score Distribution by Race",
    subtitle = "Baseline and Year 2 and year 4",
    x = "Centile Bin",
    y = "Individual Count"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# edit this plot to consider only certain races at a time
thickness_centile_male_wider %>%
  drop_na() %>%             # edit desired races below
  filter(race_ethnicity %in% c("White", "Black")) %>% 
                          # edit desired time below
  mutate(centile_bin = cut(centile_baseline, breaks = seq(0, 1, by = 0.25), include.lowest = TRUE)) %>%
  ggplot(aes(x = centile_bin, fill = race_ethnicity)) +
  geom_bar(position = "stack") +
  labs(title = "Individual Centile Scores by Race",
       x = "Centile",
       y = "Individual Count")
```

```{r}
thickness_centile_male %>% 
  group_by(src_subject_id) %>%
  filter(n() > 1) %>%  # keep only those with repeated measures
  ungroup() %>%
  filter(eventname == "baseline_year_1_arm_1") %>% 
  ggplot(aes(interview_age)) +
  geom_bar() +
  scale_x_continuous(
    name = "Age (years)",
    breaks = seq(96, 192, by = 12),
    labels = function(x) x / 12
  )

thickness_centile_male %>% 
  filter(eventname == "2_year_follow_up_y_arm_1") %>% 
  ggplot(aes(interview_age)) +
  geom_bar() + 
  scale_x_continuous(
    name = "Age (years)",
    breaks = seq(96, 192, by = 12),
    labels = function(x) x / 12
  )

thickness_centile_male %>% 
  filter(eventname == "4_year_follow_up_y_arm_1") %>% 
  ggplot(aes(interview_age)) +
  geom_bar() +
  scale_x_continuous(
    name = "Age (years)",
    breaks = seq(96, 192, by = 12),
    labels = function(x) x / 12
  )
```

