---
title: "demog_distr"
author: Jeffrey Choi
output: html_document
---
Exploring ABCD dataset and plotting demographic information
```{r}
#| warning: false

data_dir <- '/Users/jeffee/Library/CloudStorage/Box-Box/ABCD Tabulated Data/5.1/core/'

# NOTE: must run entire code chunk
if(!is.null(data_dir)){
  setwd(data_dir) # set core as working directory
}

# LOAD DATA
# Demographic variables and propensity weights
demog <- read.csv("abcd-general/abcd_p_demo.csv", na.strings = c("999", "777"))
# Age in months, Site ID (ABCD Study Design Variables), Family ID
study_covars <- read.csv("abcd-general/abcd_y_lt.csv")
# desikan atlas, average cortical thickness in mm for whole brain
dat.mri.ct = read.csv('imaging/mri_y_smr_thk_dsk.csv') %>%
  select(src_subject_id, eventname, smri_thick_cdk_mean)
# desikan atlas, total cortical surface area in mm^2 for whole brain
dat.mri.area = read.csv('imaging/mri_y_smr_area_dsk.csv') %>%
  select(src_subject_id, eventname, smri_area_cdk_total)

```

```{r}
#| label: clean-demog

# basic cleaning for demographic variables
demog_clean <- demog |>
  # filter for events of interest
  filter(eventname %in% c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1",
                          "4_year_follow_up_y_arm_1")) |>
  # select broad demographics
  select(src_subject_id, eventname, starts_with("demo_brthdat_v2"), demo_sex_v2, race_ethnicity) |>
  mutate(
    # clean age variable
    age = case_when(
      eventname == "baseline_year_1_arm_1" ~ trunc(demo_brthdat_v2), # remove decimals 
      eventname %in% c("2_year_follow_up_y_arm_1", "4_year_follow_up_y_arm_1") ~
        trunc(demo_brthdat_v2_l)),
    # broad race/ethnicity categories
    race_ethnicity = case_match(
      race_ethnicity,
      1 ~ "White",
      2 ~ "Black",
      3 ~ "Hispanic",
      4 ~ "Asian",
      5 ~ "Other"
    ),
    # recode sex variable
    sex = factor(demo_sex_v2),
    sex = fct_recode(
      sex,
      "Male" = "1",
      "Female" = "2",
      "Intersex-Male" = "3"
    ))
```

```{r}

# full dataset
thickness <- dat.mri.ct |>
  full_join(dat.mri.area, by = join_by("eventname", "src_subject_id")) |>
  # join mri data to demographics
  right_join(demog_clean, by = join_by("eventname", "src_subject_id")) |>
  # join to study covariates
  left_join(study_covars, by = join_by("eventname", "src_subject_id")) |>
  # select variables of interest
  select(src_subject_id, eventname, smri_thick_cdk_mean, smri_area_cdk_total, age, sex, site_id_l, race_ethnicity, interview_age) |>
  # remove ages less than 8 and more than 16
  filter(age < 16 & age > 8) |>
  mutate(interview_age = as.numeric(interview_age)) |>
  rename(thick = smri_thick_cdk_mean,
         area = smri_area_cdk_total) |>
  drop_na(thick, area) |>
  group_by(src_subject_id) |>
  # fill repeated demographic values
  mutate(sex = first(na.omit(sex)),
         race_ethnicity = first(na.omit(race_ethnicity)),
         # change in cortical thickness / surface area
         change = thick - thick[1],
         change_area = area - area[1],
         src_subject_id = factor(src_subject_id),
         site_id_l = factor(site_id_l),
         race_ethnicity = factor(race_ethnicity)) |>
  ungroup()
```


```{r}

# plot sex distribution
demog_clean %>%
  filter(!is.na(sex)) %>%
  ggplot(aes(x = sex)) + 
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  labs(x = "Sex", y = "Count", title = "Distribution of Sex") +
  theme_minimal()

# plot race distribution
demog_clean %>%
  filter(!is.na(race_ethnicity)) %>%
  ggplot(aes(x = race_ethnicity)) + 
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  labs(x = "Race", y = "Count", title = "Distribution of Race") +
  theme_minimal()

# stores id that have been to multiple sites
diff_sites <- thickness %>%
  group_by(src_subject_id) %>%
  summarize(
    num_visits = n(),
    num_sites = n_distinct(site_id_l)
  ) %>%
  filter(num_sites > 1)

print(diff_sites %>% count()) # how many people have been to multiple sites

# plot site distribution
thickness %>%
  anti_join(diff_sites, by = "src_subject_id") %>%
  distinct(src_subject_id, site_id_l) %>%
  ggplot(aes(x = site_id_l)) +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  labs(
    title = "Distribution of Individuals from Each Site",
    subtitle = "Excluding Individuals that have been to Multiple Sites",
    x = "Site ID",
    y = "Count"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )




```


```{r}

visit_order <- c(
  "baseline_year_1_arm_1",
  "1_year_follow_up_y_arm_1",
  "2_year_follow_up_y_arm_1",
  "3_year_follow_up_y_arm_1",
  "4_year_follow_up_y_arm_1"
)

demog %>%
  mutate(eventname = factor(eventname, levels = visit_order)) %>%
  ggplot(aes(x = eventname)) +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  labs(
    title = "Distribution of Visits",
    subtitle = "Original (abcd_p_demo.csv)",
    x = "Visit",
    y = "Count"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

demog_clean %>%
  mutate(eventname = factor(eventname, levels = visit_order)) %>%
  ggplot(aes(x = eventname)) +
  geom_bar() +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  labs(
    title = "Distribution of Visits",
    subtitle = "Filtered for baseline/year2/year4 (demog_clean)",
    x = "Visit",
    y = "Count"
  ) +
  theme_minimal()

thickness %>%
  mutate(eventname = factor(eventname, levels = visit_order)) %>%
  ggplot(aes(x = eventname)) +
  geom_bar() +
  geom_bar() +
  geom_text(stat = "count", aes(label = after_stat(count)), vjust = -0.5) +
  labs(
    title = "Distribution of Visits",
    subtitle = "Filtered by age (thickness)",
    x = "Visit",
    y = "Count"
  ) +
  theme_minimal()

```



