---
title: "residual_plotting"
author: Jeffrey Choi
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
```

Note: PRE RACE_RECODING
```{r}
data_dir <- '~/Library/CloudStorage/Box-Box/'

setwd(data_dir)

thickness_centile_male <- read.csv("thickness/final_data_male_year4_mh.csv")

thickness_centile_female <- read.csv("thickness/final_data_female_year4_mh.csv")
```

```{r}
# contains people multiple times for each race/ethnicity they are
thickness_centile_male <- thickness_centile_male %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing")) 
  # %>% 
  # mutate(race_ethnicity = case_when(
  #     "AIAN" ~ "Asian",
  #   )
  # )

thickness_centile_female <- thickness_centile_female %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing"))
```

```{r}
thickness_male_RMSE_ind_region <- thickness_centile_male %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }
```

```{r}
thickness_female_RMSE_ind_region <- thickness_centile_female %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }
```
