---
title: "race_combo_modeling"
author: Jeffrey Choi
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(ggseg)
library(stringr)
```

```{r}
race_list <- c("White", "Black", "Asian", "Hispanic", "NHPI", "AIAN", "Other")
diff_list <- c("Black", "Asian", "Hispanic", "NHPI", "AIAN", "Other")
# list of all race combos thanks chatgpt
race_combos <- unlist(
  lapply(1:length(race_list), function(k) combn(race_list, k, simplify = FALSE)),
  recursive = FALSE
)
race_diff_combos <- unlist(
  lapply(1:length(diff_list), function(k) combn(diff_list, k, simplify = FALSE)),
  recursive = FALSE
)

# function to plot each combo
make_thickness_plot <- function(data, race_subset, title, subtitle, gradient_limits) {
  filtered <- data %>% 
    filter(race_ethnicity %in% race_subset)
  
  joined <- brain_join(dk_df, filtered, by = c("region", "hemi"))

  plot <- joined %>%
    mutate(hover = paste0(region, ": ", round(RMSE_residual, 3))) %>% 
    drop_na() %>%
    group_by(race_ethnicity) %>%
    ggplot() +
    geom_brain(atlas = dk,
               position = position_brain(hemi ~ side),
               mapping = aes(fill = RMSE_residual)) +
    labs(title = title,
         subtitle = subtitle) +
    facet_wrap(~race_ethnicity) +
    scale_fill_gradientn(
      name = "RMSE in mm", 
      colors = rev(hcl.colors(10, "purple-yellow")),
      limits = gradient_limits
    ) +
    theme_void()
  
  return(plot)
}

make_area_plot <- function(data, race_subset, title, subtitle, gradient_limits) {
  filtered <- data %>% 
    filter(race_ethnicity %in% race_subset)
  
  joined <- brain_join(dk_df, filtered, by = c("region", "hemi"))

  plot <- joined %>%
    mutate(hover = paste0(region, ": ", round(RMSE_residual, 3))) %>% 
    drop_na() %>%
    group_by(race_ethnicity) %>%
    ggplot() +
    geom_brain(atlas = dk,
               position = position_brain(hemi ~ side),
               mapping = aes(fill = RMSE_residual)) +
    labs(title = title,
         subtitle = subtitle) +
    facet_wrap(~race_ethnicity) +
    scale_fill_gradientn(
      name = "RMSE in mm", 
      colors = rev(hcl.colors(10, "purple-yellow")),
      limits = gradient_limits
    ) +
    theme_void()
  
  return(plot)
}

make_difference_plot <- function(data, race_subset, title, subtitle, gradient_limits) {
  filtered <- data %>% 
    filter(race_ethnicity %in% race_subset)
  
  joined <- brain_join(dk_df, filtered, by = c("region", "hemi"))

  plot <- joined %>%
    mutate(hover = paste0(region, ": ", round(rel_diff, 3))) %>% 
    drop_na() %>%
    group_by(race_ethnicity) %>%
    ggplot() +
    geom_brain(atlas = dk,
               position = position_brain(hemi ~ side),
               mapping = aes(fill = rel_diff)) +
    labs(title = title,
         subtitle = subtitle) +
    facet_wrap(~race_ethnicity) +
    scale_fill_gradientn(
      name = "Relative Deviation from White (%)", 
      colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
      limits = gradient_limits
    ) +
    theme_void()
  
  return(plot)
}
```


```{r}
dk_abv_to_names = read.csv("~/Documents/GitHub/Normative_brain_development_and_deviations_for_adolescents/exploration/additional_files/dk_abv_to_names.csv")
# returns region name from abcd abv
get_name <- function(dk_abv_to_names, abv){
  (dk_abv_to_names %>% filter(var_name == abv))$region
}
```

First lets look at thickness, raw rmse
```{r}
data_dir <- '~/Library/CloudStorage/Box-Box/'

setwd(data_dir)

thickness_centile_male <- read.csv("thickness/final_data_male_year4_mh.csv")

thickness_centile_female <- read.csv("thickness/final_data_female_year4_mh.csv")

thickness_male_RMSE_ind_region <- thickness_centile_male %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }

thickness_female_RMSE_ind_region <- thickness_centile_female %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }
```

```{r}
thickness_male_RMSE_ind_region <- thickness_male_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()


thickness_female_RMSE_ind_region <- thickness_female_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

dk_df <- as_tibble(dk)
thickness_male_RMSE_ind_region <- thickness_male_RMSE_ind_region %>% 
  filter(!region_raw %in% 
           c("smri_thick_cdk_mean.combat", 
             "smri_thick_cdk_meanlh.combat",
             "smri_thick_cdk_meanrh.combat"))
```

```{r}
male_plot_list <- list()
female_plot_list <- list()

for (combo in race_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_plot_list[[race_label]] <- make_thickness_plot(
    thickness_male_RMSE_ind_region,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)",
    subtitle = "Male",
    gradient_limits = c(0.04, 0.41)
  )
  
  female_plot_list[[race_label]] <- make_thickness_plot(
    thickness_female_RMSE_ind_region,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)", 
    subtitle = "Female",
    gradient_limits = c(0.04, 0.41)
  )
}
```

```{r}
male_plot_list[[127]]
female_plot_list[[127]]
```

```{r}
thickness_male_RMSE_ind_region_long <- thickness_centile_male %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

thickness_male_RMSE_ind_region_event <- thickness_male_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_thickness_male_RMSE_ind_region_event <- thickness_male_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

thickness_male_RMSE_ind_region_event <- bind_rows(
  thickness_male_RMSE_ind_region_event,
  overall_thickness_male_RMSE_ind_region_event
)

thickness_male_RMSE <- thickness_male_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere"))

thickness_male_RMSE_baseline <- thickness_male_RMSE %>% 
  filter(event_time == "Baseline")

thickness_male_RMSE_year2 <- thickness_male_RMSE %>% 
  filter(event_time == "Year 2")

thickness_male_RMSE_year4 <- thickness_male_RMSE %>% 
  filter(event_time == "Year 4")

thickness_female_RMSE_ind_region_long <- thickness_centile_female %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

thickness_female_RMSE_ind_region_event <- thickness_female_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_thickness_female_RMSE_ind_region_event <- thickness_female_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

thickness_female_RMSE_ind_region_event <- bind_rows(
  thickness_female_RMSE_ind_region_event,
  overall_thickness_female_RMSE_ind_region_event
)

thickness_female_RMSE <- thickness_female_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere"))

thickness_female_RMSE_baseline <- thickness_female_RMSE %>% 
  filter(event_time == "Baseline")

thickness_female_RMSE_year2 <- thickness_female_RMSE %>% 
  filter(event_time == "Year 2")

thickness_female_RMSE_year4 <- thickness_female_RMSE %>% 
  filter(event_time == "Year 4")
```

```{r}
male_baseline_plot_list <- list()
female_baseline_plot_list <- list()
male_year2_plot_list <- list()
female_year2_plot_list <- list()
male_year4_plot_list <- list()
female_year4_plot_list <- list()

for (combo in race_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_baseline_plot_list[[race_label]] <- make_thickness_plot(
    thickness_male_RMSE_baseline,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)", 
    subtitle = "Baseline Male",
    gradient_limits = c(0.04, 0.41)
  )
  
  female_baseline_plot_list[[race_label]] <- make_thickness_plot(
    thickness_female_RMSE_baseline,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)", 
    subtitle = "Baseline Female",
    gradient_limits = c(0.04, 0.41)
  )
  
  male_year2_plot_list[[race_label]] <- make_thickness_plot(
    thickness_male_RMSE_year2,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)", 
    subtitle = "Year 2 Male",
    gradient_limits = c(0.04, 0.41)
  )
  
  female_year2_plot_list[[race_label]] <- make_thickness_plot(
    thickness_female_RMSE_year2,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)", 
    subtitle = "Year 2 Female",
    gradient_limits = c(0.04, 0.41)
  )
  
  male_year4_plot_list[[race_label]] <- make_thickness_plot(
    thickness_male_RMSE_year4,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)", 
    subtitle = "Year 4 Male",
    gradient_limits = c(0.04, 0.41)
  )
  
  female_year4_plot_list[[race_label]] <- make_thickness_plot(
    thickness_female_RMSE_year4,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Thickness)", 
    subtitle = "Year 4 Female",
    gradient_limits = c(0.04, 0.41)
  )
}
```

```{r}
male_baseline_plot_list[[127]]
female_baseline_plot_list[[127]]
male_year2_plot_list[[127]]
female_year2_plot_list[[127]]
male_year4_plot_list[[127]]
female_year4_plot_list[[127]]
```

Surface Area Time
```{r}
data_dir <- '~/Library/CloudStorage/Box-Box/'

setwd(data_dir)

area_centile_male <- read.csv("area/final_data_male_year4_mh.csv")
area_centile_female <- read.csv("area/final_data_female_year4_mh.csv")

# contains people multiple times for each race/ethnicity they are
area_centile_male <- area_centile_male %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing")) 

area_centile_female <- area_centile_female %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing"))

area_male_RMSE_ind_region <- area_centile_male %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }

area_female_RMSE_ind_region <- area_centile_female %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }

area_male_RMSE_ind_region <- area_male_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

area_female_RMSE_ind_region <- area_female_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()
```

```{r}
male_area_plot_list <- list()
female_area_plot_list <- list()

for (combo in race_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_area_plot_list[[race_label]] <- make_area_plot(
    area_male_RMSE_ind_region,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)",
    subtitle = "Male",
    gradient_limits = c(26, 1459.3)
  )
  
  female_area_plot_list[[race_label]] <- make_area_plot(
    area_female_RMSE_ind_region,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)", 
    subtitle = "Female",
    gradient_limits = c(26, 1459.3)
  )
}
```

```{r}
male_area_plot_list[[127]]
female_area_plot_list[[127]]
```

```{r}
area_male_RMSE_ind_region_long <- area_centile_male %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

area_male_RMSE_ind_region_event <- area_male_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_area_male_RMSE_ind_region_event <- area_male_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

area_male_RMSE_ind_region_event <- bind_rows(
  area_male_RMSE_ind_region_event,
  overall_area_male_RMSE_ind_region_event
)

area_male_RMSE <- area_male_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

area_male_RMSE_baseline <- area_male_RMSE %>% 
  filter(event_time == "Baseline")

area_male_RMSE_year2 <- area_male_RMSE %>% 
  filter(event_time == "Year 2")

area_male_RMSE_year4 <- area_male_RMSE %>% 
  filter(event_time == "Year 4")

area_female_RMSE_ind_region_long <- area_centile_female %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

area_female_RMSE_ind_region_event <- area_female_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_area_female_RMSE_ind_region_event <- area_female_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

area_female_RMSE_ind_region_event <- bind_rows(
  area_female_RMSE_ind_region_event,
  overall_area_female_RMSE_ind_region_event
)

area_female_RMSE <- area_female_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

area_female_RMSE_baseline <- area_female_RMSE %>% 
  filter(event_time == "Baseline")

area_female_RMSE_year2 <- area_female_RMSE %>% 
  filter(event_time == "Year 2")

area_female_RMSE_year4 <- area_female_RMSE %>% 
  filter(event_time == "Year 4")
```

```{r}
male_baseline_area_plot_list <- list()
female_baseline_area_plot_list <- list()
male_year2_area_plot_list <- list()
female_year2_area_plot_list <- list()
male_year4_area_plot_list <- list()
female_year4_area_plot_list <- list()

for (combo in race_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_baseline_area_plot_list[[race_label]] <- make_area_plot(
    area_male_RMSE_baseline,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)", 
    subtitle = "Baseline Male",
    gradient_limits = c(26, 1459.3)
  )
  
  female_baseline_area_plot_list[[race_label]] <- make_area_plot(
    area_female_RMSE_baseline,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)", 
    subtitle = "Baseline Female",
    gradient_limits = c(26, 1459.3)
  )
  
  male_year2_area_plot_list[[race_label]] <- make_area_plot(
    area_male_RMSE_year2,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)", 
    subtitle = "Year 2 Male",
    gradient_limits = c(26, 1459.3)
  )
  
  female_year2_area_plot_list[[race_label]] <- make_area_plot(
    area_female_RMSE_year2,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)", 
    subtitle = "Year 2 Female",
    gradient_limits = c(26, 1459.3)
  )
  
  male_year4_area_plot_list[[race_label]] <- make_area_plot(
    area_male_RMSE_year4,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)", 
    subtitle = "Year 4 Male",
    gradient_limits = c(26, 1459.3)
  )
  
  female_year4_area_plot_list[[race_label]] <- make_area_plot(
    area_female_RMSE_year4,
    race_subset = combo,
    title = "Average Residual From Predicted Curve by Race/Ethnicity (Cortical Surface Area)", 
    subtitle = "Year 4 Female",
    gradient_limits = c(26, 1459.3)
  )
}
```

```{r}
male_baseline_area_plot_list[[127]]
female_baseline_area_plot_list[[127]]
male_year2_area_plot_list[[127]]
female_year2_area_plot_list[[127]]
male_year4_area_plot_list[[127]]
female_year4_area_plot_list[[127]]
```

Now lets look at the difference of residuals from whites
```{r}
thickness_male_RMSE_ind_region <- thickness_centile_male %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }

thickness_female_RMSE_ind_region <- thickness_centile_female %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }

thickness_male_RMSE_ind_region <- thickness_male_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()


thickness_female_RMSE_ind_region <- thickness_female_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

male_plot_df <- thickness_male_RMSE_ind_region %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere")) %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

female_plot_df <- thickness_female_RMSE_ind_region %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere")) %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")
```

```{r}
male_difference_plot_list <- list()
female_difference_plot_list <- list()

for (combo in race_diff_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_difference_plot_list[[race_label]] <- make_difference_plot(
    male_plot_df,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Male",
    gradient_limits = c(-0.53, 0.53)
  )
  
  female_difference_plot_list[[race_label]] <- make_difference_plot(
    female_plot_df,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Female",
    gradient_limits = c(-0.53, 0.53)
  )
}
```

```{r}
male_difference_plot_list[[63]]
female_difference_plot_list[[63]]
```

Now for each timepoint
```{r}
thickness_male_RMSE_ind_region_long <- thickness_centile_male %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

thickness_male_RMSE_ind_region_event <- thickness_male_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_thickness_male_RMSE_ind_region_event <- thickness_male_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

thickness_male_RMSE_ind_region_event <- bind_rows(
  thickness_male_RMSE_ind_region_event,
  overall_thickness_male_RMSE_ind_region_event
)

thickness_male_RMSE <- thickness_male_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere"))

thickness_male_RMSE_baseline <- thickness_male_RMSE %>% 
  filter(event_time == "Baseline") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

thickness_male_RMSE_year2 <- thickness_male_RMSE %>% 
  filter(event_time == "Year 2") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

thickness_male_RMSE_year4 <- thickness_male_RMSE %>% 
  filter(event_time == "Year 4") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

thickness_female_RMSE_ind_region_long <- thickness_centile_female %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

thickness_female_RMSE_ind_region_event <- thickness_female_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_thickness_female_RMSE_ind_region_event <- thickness_female_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

thickness_female_RMSE_ind_region_event <- bind_rows(
  thickness_female_RMSE_ind_region_event,
  overall_thickness_female_RMSE_ind_region_event
)

thickness_female_RMSE <- thickness_female_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere"))

thickness_female_RMSE_baseline <- thickness_female_RMSE %>% 
  filter(event_time == "Baseline") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

thickness_female_RMSE_year2 <- thickness_female_RMSE %>% 
  filter(event_time == "Year 2") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White")%>% 
  filter(race_ethnicity != "Missing")

thickness_female_RMSE_year4 <- thickness_female_RMSE %>% 
  filter(event_time == "Year 4") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White")%>% 
  filter(race_ethnicity != "Missing")
```

```{r}
male_difference_baseline_plot_list <- list()
female_difference_baseline_plot_list <- list()
male_difference_year2_plot_list <- list()
female_difference_year2_plot_list <- list()
male_difference_year4_plot_list <- list()
female_difference_year4_plot_list <- list()

for (combo in race_diff_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_difference_baseline_plot_list[[race_label]] <- make_difference_plot(
    thickness_male_RMSE_baseline,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Baseline Male",
    gradient_limits = c(-0.53, 0.53)
  )
  
  female_difference_baseline_plot_list[[race_label]] <- make_difference_plot(
    thickness_female_RMSE_baseline,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Baseline Female",
    gradient_limits = c(-0.53, 0.53)
  )
  
  male_difference_year2_plot_list[[race_label]] <- make_difference_plot(
    thickness_male_RMSE_year2,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Year 2 Male",
    gradient_limits = c(-0.53, 0.53)
  )
  
  female_difference_year2_plot_list[[race_label]] <- make_difference_plot(
    thickness_female_RMSE_year2,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Year 2 Female",
    gradient_limits = c(-0.53, 0.53)
  )
  
  male_difference_year4_plot_list[[race_label]] <- make_difference_plot(
    thickness_male_RMSE_year4,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Year 4 Male",
    gradient_limits = c(-0.53, 0.53)
  )
  
  female_difference_year4_plot_list[[race_label]] <- make_difference_plot(
    thickness_female_RMSE_year4,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Thickness)",
    subtitle = "Year 4 Female",
    gradient_limits = c(-0.53, 0.53)
  )
}
```

```{r}
male_difference_baseline_plot_list[[63]]
female_difference_baseline_plot_list[[63]]
male_difference_year2_plot_list[[63]]
female_difference_year2_plot_list[[63]]
male_difference_year4_plot_list[[63]]
female_difference_year4_plot_list[[63]]
```

Surface Area Time
```{r}
area_male_RMSE_ind_region <- area_centile_male %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }

area_female_RMSE_ind_region <- area_centile_female %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }

area_male_RMSE_ind_region <- area_male_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_female_RMSE_ind_region <- area_female_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")
```

```{r}
male_difference_area_plot_list <- list()
female_difference_area_plot_list <- list()

for (combo in race_diff_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_difference_area_plot_list[[race_label]] <- make_difference_plot(
    area_male_RMSE_ind_region,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Male",
    gradient_limits = c(-0.3, 0.3)
  )
  
  female_difference_area_plot_list[[race_label]] <- make_difference_plot(
    area_female_RMSE_ind_region,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Female",
    gradient_limits = c(-0.3, 0.3)
  )
}
```

```{r}
male_difference_area_plot_list[[63]]
female_difference_area_plot_list[[63]]
```

```{r}
area_male_RMSE_ind_region_long <- area_centile_male %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

area_male_RMSE_ind_region_event <- area_male_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_area_male_RMSE_ind_region_event <- area_male_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

area_male_RMSE_ind_region_event <- bind_rows(
  area_male_RMSE_ind_region_event,
  overall_area_male_RMSE_ind_region_event
)

area_male_RMSE <- area_male_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

area_male_RMSE_baseline <- area_male_RMSE %>% 
  filter(event_time == "Baseline") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_male_RMSE_year2 <- area_male_RMSE %>% 
  filter(event_time == "Year 2") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_male_RMSE_year4 <- area_male_RMSE %>% 
  filter(event_time == "Year 4") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_female_RMSE_ind_region_long <- area_centile_female %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

area_female_RMSE_ind_region_event <- area_female_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_area_female_RMSE_ind_region_event <- area_female_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

area_female_RMSE_ind_region_event <- bind_rows(
  area_female_RMSE_ind_region_event,
  overall_area_female_RMSE_ind_region_event
)

area_female_RMSE <- area_female_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

area_female_RMSE_baseline <- area_female_RMSE %>% 
  filter(event_time == "Baseline") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_female_RMSE_year2 <- area_female_RMSE %>% 
  filter(event_time == "Year 2") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_female_RMSE_year4 <- area_female_RMSE %>% 
  filter(event_time == "Year 4") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")
```

```{r}
male_difference_baseline_area_plot_list <- list()
female_difference_baseline_area_plot_list <- list()
male_difference_year2_area_plot_list <- list()
female_difference_year2_area_plot_list <- list()
male_difference_year4_area_plot_list <- list()
female_difference_year4_area_plot_list <- list()

for (combo in race_diff_combos) {
  race_label <- paste(combo, collapse = "_")
  
  male_difference_baseline_area_plot_list[[race_label]] <- make_difference_plot(
    area_male_RMSE_baseline,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Baseline Male",
    gradient_limits = c(-0.91, 0.91)
  )
  
  female_difference_baseline_area_plot_list[[race_label]] <- make_difference_plot(
    area_female_RMSE_baseline,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Baseline Female",
    gradient_limits = c(-0.91, 0.91)
  )
  
  male_difference_year2_area_plot_list[[race_label]] <- make_difference_plot(
    area_male_RMSE_year2,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Year 2 Male",
    gradient_limits = c(-0.91, 0.91)
  )
  
  female_difference_year2_area_plot_list[[race_label]] <- make_difference_plot(
    area_female_RMSE_year2,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Year 2 Female",
    gradient_limits = c(-0.91, 0.91)
  )
  
  male_difference_year4_area_plot_list[[race_label]] <- make_difference_plot(
    area_male_RMSE_year4,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Year 4 Male",
    gradient_limits = c(-0.91, 0.91)
  )
  
  female_difference_year4_area_plot_list[[race_label]] <- make_difference_plot(
    area_female_RMSE_year4,
    race_subset = combo,
    title = "Difference in Residuals from White (Cortical Surface Area)",
    subtitle = "Year 4 Female",
    gradient_limits = c(-0.91, 0.91)
  )
}
```

```{r}
male_difference_baseline_area_plot_list[[63]]
female_difference_baseline_area_plot_list[[63]]
male_difference_year2_area_plot_list[[63]]
female_difference_year2_area_plot_list[[63]]
male_difference_year4_area_plot_list[[63]]
female_difference_year4_area_plot_list[[63]]
```


