---
title: "residual_plotting"
author: Jeffrey Choi
output: html_document
---

Now we take the difference of a reference group for each race
```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(ggseg)
library(stringr)
```

Thickness First
```{r}
data_dir <- '~/Library/CloudStorage/Box-Box/'

setwd(data_dir)

thickness_centile_male <- read.csv("thickness/final_data_male_year4_mh.csv")

thickness_centile_female <- read.csv("thickness/final_data_female_year4_mh.csv")
```

```{r}
# contains people multiple times for each race/ethnicity they are
thickness_centile_male <- thickness_centile_male %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing")) 

thickness_centile_female <- thickness_centile_female %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing"))
```

```{r}
thickness_male_RMSE_ind_region <- thickness_centile_male %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }
```

```{r}
thickness_female_RMSE_ind_region <- thickness_centile_female %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }
```

```{r}
dk_abv_to_names = read.csv("~/Documents/GitHub/Normative_brain_development_and_deviations_for_adolescents/exploration/additional_files/dk_abv_to_names.csv")
# returns region name from abcd abv
get_name <- function(dk_abv_to_names, abv){
  (dk_abv_to_names %>% filter(var_name == abv))$region
}
```

```{r}
thickness_male_RMSE_ind_region <- thickness_male_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()


thickness_female_RMSE_ind_region <- thickness_female_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()
```

```{r}
dk_df <- as_tibble(dk)

male_plot_df <- thickness_male_RMSE_ind_region %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere")) %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing") %>% 
  filter(race_ethnicity != "All")
  
male_joined <- brain_join(dk_df, male_plot_df, by = c("region", "hemi"))

male_plot <- male_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-32, 32)
  ) +
  theme_void()

female_plot_df <- thickness_female_RMSE_ind_region %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere")) %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing") %>% 
  filter(race_ethnicity != "All")

female_joined <- brain_join(dk_df, female_plot_df, by = c("region", "hemi"))

female_plot <- female_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-32, 32)
  ) +
  theme_void()

male_plot
ggsave("~/Library/CloudStorage/Box-Box/male_thickness_difference.png", plot = male_plot)
female_plot
ggsave("~/Library/CloudStorage/Box-Box/male_thickness_difference.png", plot = female_plot)
```
```{r}
male_plot_df %>% 
  group_by(race_ethnicity) %>% 
  summarise(mean(rel_diff))

female_plot_df %>% 
  group_by(race_ethnicity) %>% 
  summarise(mean(rel_diff))
```

At each visit
Males first
```{r}
thickness_male_RMSE_ind_region_long <- thickness_centile_male %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

thickness_male_RMSE_ind_region_event <- thickness_male_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_thickness_male_RMSE_ind_region_event <- thickness_male_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

thickness_male_RMSE_ind_region_event <- bind_rows(
  thickness_male_RMSE_ind_region_event,
  overall_thickness_male_RMSE_ind_region_event
)
```

```{r}
thickness_male_RMSE <- thickness_male_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere"))

thickness_male_RMSE_baseline <- thickness_male_RMSE %>% 
  filter(event_time == "Baseline") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

thickness_male_RMSE_year2 <- thickness_male_RMSE %>% 
  filter(event_time == "Year 2") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

thickness_male_RMSE_year4 <- thickness_male_RMSE %>% 
  filter(event_time == "Year 4") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")
  
male_baseline_joined <- brain_join(dk_df, thickness_male_RMSE_baseline, by = c("region", "hemi"))
male_year2_joined <- brain_join(dk_df, thickness_male_RMSE_year2, by = c("region", "hemi"))
male_year4_joined <- brain_join(dk_df, thickness_male_RMSE_year4, by = c("region", "hemi"))

male_baseline_plot <- male_baseline_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Baseline Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-53, 53)
  ) +
  theme_void()

male_year2_plot <- male_year2_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Year 2 Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-53, 53)
  ) +
  theme_void()

male_year4_plot <- male_year4_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Year 4 Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-53, 53)
  ) +
  theme_void()

male_baseline_plot
ggsave("~/Library/CloudStorage/Box-Box/male_ct_baseline.png", plot = male_baseline_plot)
male_year2_plot
ggsave("~/Library/CloudStorage/Box-Box/male_ct_year2.png", plot = male_year2_plot)
male_year4_plot
ggsave("~/Library/CloudStorage/Box-Box/male_ct_year4.png", plot = male_year4_plot)
```

Now Females
```{r}
thickness_female_RMSE_ind_region_long <- thickness_centile_female %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

thickness_female_RMSE_ind_region_event <- thickness_female_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_thickness_female_RMSE_ind_region_event <- thickness_female_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

thickness_female_RMSE_ind_region_event <- bind_rows(
  thickness_female_RMSE_ind_region_event,
  overall_thickness_female_RMSE_ind_region_event
)
```

```{r}
thickness_female_RMSE <- thickness_female_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_thick_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  filter(!region %in% 
           c("Mean cortical thickness for whole brain", 
             "Mean cortical thickness for left hemisphere",
             "Mean cortical thickness for right hemisphere"))

thickness_female_RMSE_baseline <- thickness_female_RMSE %>% 
  filter(event_time == "Baseline") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

thickness_female_RMSE_year2 <- thickness_female_RMSE %>% 
  filter(event_time == "Year 2") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White")%>% 
  filter(race_ethnicity != "Missing")

thickness_female_RMSE_year4 <- thickness_female_RMSE %>% 
  filter(event_time == "Year 4") %>%
  group_by(region_raw) %>% 
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White")%>% 
  filter(race_ethnicity != "Missing")
  
female_baseline_joined <- brain_join(dk_df, thickness_female_RMSE_baseline, by = c("region", "hemi"))
female_year2_joined <- brain_join(dk_df, thickness_female_RMSE_year2, by = c("region", "hemi"))
female_year4_joined <- brain_join(dk_df, thickness_female_RMSE_year4, by = c("region", "hemi"))

female_baseline_plot <- female_baseline_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Baseline Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-53, 53)
  ) +
  theme_void()

female_year2_plot <- female_year2_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Year 2 Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-53, 53)
  ) +
  theme_void()

female_year4_plot <- female_year4_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Thickness)",
       subtitle = "Year 4 Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-53, 53)
  ) +
  theme_void()

female_baseline_plot
ggsave("~/Library/CloudStorage/Box-Box/female_ct_baseline.png", plot = female_baseline_plot)
female_year2_plot
ggsave("~/Library/CloudStorage/Box-Box/female_ct_year2.png", plot = female_year2_plot)
female_year4_plot
ggsave("~/Library/CloudStorage/Box-Box/female_ct_year4.png", plot = female_year4_plot)
```

Surface Area Now
```{r}
data_dir <- '~/Library/CloudStorage/Box-Box/'

setwd(data_dir)

area_centile_male <- read.csv("area/final_data_male_year4_mh.csv")

area_centile_female <- read.csv("area/final_data_female_year4_mh.csv")
```

```{r}
# contains people multiple times for each race/ethnicity they are
area_centile_male <- area_centile_male %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing")) 

area_centile_female <- area_centile_female %>% 
  pivot_longer(cols = c(White_race, Black_race, AIAN_race, NHPI_race,
         Asian_race, Other_race, Missing_race, demo_ethn_v2),
    names_to = "race_ethnicity",
    values_to = "indicator") %>% 
  filter(indicator == 1) %>%
  select(-indicator) %>% 
  # recode race_ethnicity variable names 
  mutate(race_ethnicity = recode(race_ethnicity, White_race = "White",
                                 demo_ethn_v2 = "Hispanic", Black_race =  "Black",
                                 AIAN_race =  "AIAN", NHPI_race =  "NHPI",
                                 Asian_race = "Asian", Other_race = "Other",
                                 Missing_race = "Missing"))
```

```{r}
area_male_RMSE_ind_region <- area_centile_male %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }
```

```{r}
area_female_RMSE_ind_region <- area_centile_female %>% 
  mutate(
    residual_sqr_baseline = residual_baseline_year_1_arm_1^2,
    residual_sqr_year2 = residual_2_year_follow_up_y_arm_1^2,
    residual_sqr_year4 = residual_4_year_follow_up_y_arm_1^2
  ) %>% 
  rowwise() %>%
  mutate(average_residual_sqr = mean(
    c(residual_sqr_baseline, residual_sqr_year2, residual_sqr_year4), 
    na.rm = TRUE
  )) %>%
  ungroup() %>%
  {
    race_region_RMSE <- group_by(., current_col_name, race_ethnicity) %>%
      summarize(
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    overall_region_RMSE <- group_by(., current_col_name) %>%
      summarize(
        race_ethnicity = "All",
        RMSE_residual = sqrt(mean(average_residual_sqr, na.rm = TRUE)),
        .groups = "drop"
      ) %>%
      rename(region_raw = current_col_name)
    
    bind_rows(race_region_RMSE, overall_region_RMSE)
  }
```

```{r}
dk_abv_to_names = read.csv("~/Documents/GitHub/Normative_brain_development_and_deviations_for_adolescents/exploration/additional_files/dk_abv_to_names.csv")
# returns region name from abcd abv
get_name <- function(dk_abv_to_names, abv){
  (dk_abv_to_names %>% filter(var_name == abv))$region
}
```

```{r}
area_male_RMSE_ind_region <- area_male_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_female_RMSE_ind_region <- area_female_RMSE_ind_region %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup() %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")
```

```{r}
dk_df <- as_tibble(dk)
  
male_joined <- brain_join(dk_df, area_male_RMSE_ind_region, by = c("region", "hemi"))

male_plot <- male_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-31, 31)
  ) +
  theme_void()

female_joined <- brain_join(dk_df, area_female_RMSE_ind_region, by = c("region", "hemi"))

female_plot <- female_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-31, 31)
  ) +
  theme_void()

male_plot
ggsave("~/Library/CloudStorage/Box-Box/male_sa_overall.png", plot = male_plot)
female_plot
ggsave("~/Library/CloudStorage/Box-Box/female_sa_overall.png", plot = female_plot)
```

At each visit
Males first
```{r}
area_male_RMSE_ind_region_long <- area_centile_male %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

area_male_RMSE_ind_region_event <- area_male_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_area_male_RMSE_ind_region_event <- area_male_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

area_male_RMSE_ind_region_event <- bind_rows(
  area_male_RMSE_ind_region_event,
  overall_area_male_RMSE_ind_region_event
)
```

```{r}
area_male_RMSE <- area_male_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

area_male_RMSE_baseline <- area_male_RMSE %>% 
  filter(event_time == "Baseline") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_male_RMSE_year2 <- area_male_RMSE %>% 
  filter(event_time == "Year 2") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_male_RMSE_year4 <- area_male_RMSE %>% 
  filter(event_time == "Year 4") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")
  
male_baseline_joined <- brain_join(dk_df, area_male_RMSE_baseline, by = c("region", "hemi"))
male_year2_joined <- brain_join(dk_df, area_male_RMSE_year2, by = c("region", "hemi"))
male_year4_joined <- brain_join(dk_df, area_male_RMSE_year4, by = c("region", "hemi"))

male_baseline_plot <- male_baseline_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Baseline Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-61, 61)
  ) +
  theme_void()

male_year2_plot <- male_year2_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Year 2 Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-61, 61)
  ) +
  theme_void()

male_year4_plot <- male_year4_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Year 4 Male") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-61, 61)
  ) +
  theme_void()

male_baseline_plot
ggsave("~/Library/CloudStorage/Box-Box/male_sa_baseline.png", plot = male_baseline_plot)
male_year2_plot
ggsave("~/Library/CloudStorage/Box-Box/male_sa_year2.png", plot = male_year2_plot)
male_year4_plot
ggsave("~/Library/CloudStorage/Box-Box/male_sa_year4.png", plot = male_year4_plot)
```

Now Females
```{r}
area_female_RMSE_ind_region_long <- area_centile_female %>% 
  select(current_col_name, race_ethnicity, 
         residual_baseline_year_1_arm_1, 
         residual_2_year_follow_up_y_arm_1, 
         residual_4_year_follow_up_y_arm_1) %>%
  pivot_longer(
    cols = starts_with("residual_"),
    names_to = "event_time",
    values_to = "residual"
  ) %>%
  mutate(residual_sqr = residual^2) %>%
  mutate(event_time = case_when(
    str_detect(event_time, "baseline") ~ "Baseline",
    str_detect(event_time, "2_year") ~ "Year 2",
    str_detect(event_time, "4_year") ~ "Year 4"
  ))

area_female_RMSE_ind_region_event <- area_female_RMSE_ind_region_long %>%
  group_by(current_col_name, race_ethnicity, event_time) %>%
  summarize(
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

overall_area_female_RMSE_ind_region_event <- area_female_RMSE_ind_region_long %>%
  group_by(current_col_name, event_time) %>%
  summarize(
    race_ethnicity = "All",
    RMSE_residual = sqrt(mean(residual_sqr, na.rm = TRUE)),
    .groups = "drop"
  ) %>%
  rename(region_raw = current_col_name)

area_female_RMSE_ind_region_event <- bind_rows(
  area_female_RMSE_ind_region_event,
  overall_area_female_RMSE_ind_region_event
)
```

```{r}
area_female_RMSE <- area_female_RMSE_ind_region_event %>%
  mutate(
    abv = str_remove(region_raw, "^smri_area_cdk_"),
    abv = str_remove(abv, "\\.combat$")
  ) %>% 
  mutate(
    hemi = case_when(
      str_detect(abv, "lh$") ~ "left",
      str_detect(abv, "rh$") ~ "right",
      TRUE ~ NA_character_
    )
  ) %>% 
  filter(!abv %in% 
           c("total", "totallh", "totalrh")) %>% 
  rowwise() %>%
  mutate(region = get_name(dk_abv_to_names, abv)) %>%
  ungroup()

area_female_RMSE_baseline <- area_female_RMSE %>% 
  filter(event_time == "Baseline") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_female_RMSE_year2 <- area_female_RMSE %>% 
  filter(event_time == "Year 2") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")

area_female_RMSE_year4 <- area_female_RMSE %>% 
  filter(event_time == "Year 4") %>% 
  group_by(region_raw) %>%
  mutate(
    all_value = RMSE_residual[race_ethnicity == "White"],
    diff = RMSE_residual - all_value,
    rel_diff = (RMSE_residual - all_value) / all_value
  ) %>% 
  filter(race_ethnicity != "White") %>% 
  filter(race_ethnicity != "Missing")
  
female_baseline_joined <- brain_join(dk_df, area_female_RMSE_baseline, by = c("region", "hemi"))
female_year2_joined <- brain_join(dk_df, area_female_RMSE_year2, by = c("region", "hemi"))
female_year4_joined <- brain_join(dk_df, area_female_RMSE_year4, by = c("region", "hemi"))

female_baseline_plot <- female_baseline_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Baseline Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-61, 61)
  ) +
  theme_void()

female_year2_plot <- female_year2_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Year 2 Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-61, 61)
  ) +
  theme_void()

female_year4_plot <- female_year4_joined %>%
  mutate(hover = paste0(region, ": ", round(rel_diff, 4))) %>% 
  drop_na() %>% 
  group_by(race_ethnicity) %>%
  ggplot() +
  geom_brain(atlas = dk,
             position = position_brain(hemi ~ side),
             mapping = aes(fill = rel_diff * 100)) +
  labs(title = "Difference in Residuals from White (Cortical Surface Area)",
       subtitle = "Year 4 Female") +
  facet_wrap(~race_ethnicity) +
  scale_fill_gradientn(
    name = "Relative Deviation from White (%)",
    colors = c("#4575b4", "#78acf1", "white", "#ef726b", "#d73027"),
    limits = c(-61, 61)
  ) +
  theme_void()

female_baseline_plot
ggsave("~/Library/CloudStorage/Box-Box/female_sa_baseline.png", plot = female_baseline_plot)
female_year2_plot
ggsave("~/Library/CloudStorage/Box-Box/female_sa_year2.png", plot = female_year2_plot)
female_year4_plot
ggsave("~/Library/CloudStorage/Box-Box/female_sa_year4.png", plot = female_year4_plot)
```
